ML coding

In [2]:
import numpy as np

# List to array and array to List

list -> array: array(a),asarray(a)
array -> list: x.tolist()

In [ ]:
# From an existing ndarray → no copy (same object)
arr = np.array([1, 2, 3])
y = np.asarray(arr)
print(y is arr)  # True

# Compare with np.array, which always copies by default
z = np.array(arr)
print(z is arr)  # False


# Multiplication

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.T@b)

print(a@b)
print(np.dot(a,b))
print(a*b)
print(sum(a*b))
try:
    print([1,2,3]*[4,5,6])
except Exception as e:
    print("Error: " + str(e))

    
    # raise Exception("This trial doesn't work") from e

32
32
32
[ 4 10 18]
32
Error: can't multiply sequence by non-int of type 'list'


constant mean here

1:07 PM
(1,1), (1,1) — one tuple per dimension:

(1, 1)  → add 1 row on TOP,    1 row on BOTTOM
(1, 1)  → add 1 col on LEFT,   1 col on RIGHT
'constant' — fill the padded area with a constant value (default = 0). Other modes exist:

mode	meaning	example border
'constant'	fill with a fixed value (default 0)	0 0 0 0
'reflect'	mirror the values	4 3 4 3
'edge'	repeat the edge value	1 1 1 2

# unique(a)

In [11]:
y = np.array([0, 1, 2, 2, 0])
np.unique(y)

array([0, 1, 2])

In [17]:
W1 = np.random.randn(3, 4)
a = np.array([1, 2, 3, 4])
b = np.array([2,3,4])
print(W1@a)
print(np.dot(W1, a))
print(b@W1)
print(W1.T@b)


[-4.47217041 -5.96510724  3.59826329]
[-4.47217041 -5.96510724  3.59826329]
[  2.73492459   7.52518114 -10.80615996   0.5466459 ]
[  2.73492459   7.52518114 -10.80615996   0.5466459 ]


In [20]:
print(range(3))

range(0, 3)


L=N1​i=1∑N​−log(pi​)
This is the final cross-entropy loss — the lower it is, the better your model is at assigning high probability to the correct class.

In [ ]:
probs = np.array([[0.7, 0.2, 0.1],   # sample 0: prob for each class
                  [0.1, 0.5, 0.4],   # sample 1
                  [0.2, 0.3, 0.5]])
X = np.array([0, 1, 2])
y = np.array([0, 1, 2])
print(probs[range(len(X)), y])
correct_logprobs = -np.log(probs[range(len(X)), y])# get [0,y[0]], [1,y[1]], [2,y[2]] from probs
data_loss = np.sum(correct_logprobs)
print(1.0/len(X) * data_loss)

IndexError: index 5 is out of bounds for axis 1 with size 3

# np.random

In [3]:
import numpy as np
np.random.randint(1,4)
a = np.random.randint(1,4, (2,2))
print(a)

print(np.argmax(a, axis=0))

[[2 3]
 [1 2]]
[0 0]
